[package]

name = "http2parse"
version = "0.0.1"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>"]
repository = "https://github.com/reem/rust-http2parse.git"
description = "An HTTP2 frame parser."
readme = "README.md"
license = "MIT"

